name: Weekly Asana Report

on:
  schedule:
    # Runs every Monday at 12:00 UTC (08:00 ET)
    - cron: '0 12 * * 1'

jobs:
  report:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install requests

      - name: Generate Markdown report
        id: gen
        env:
          ASANA_PAT:        ${{ secrets.ASANA_PAT }}
          ASANA_REPORT_GID: ${{ secrets.ASANA_REPORT_GID }}
        run: |
          python generate_report.py > report.md
          echo "::set-output name=table::$(cat report.md)"

      # Option A: send via email
        if: false
        name: Send email
        uses: dawidd6/action-send-mail@v3
        if: always()
        with:
          server_address: smtp.gmail.com
          server_port: 587
          username: ${{ secrets.EMAIL_USER }}
          password: ${{ secrets.EMAIL_PASS }}
          subject: Weekly Web Dev Milestones
          to: team@example.com
          body: |
            Here’s this week’s Asana milestones:
            ${{ steps.gen.outputs.table }} 
    

      # Option B: post to Slack
      - name: Post to Slack
        if: false  # set to true and disable the email step if you prefer Slack
        uses: slackapi/slack-github-action@v1
        with:
          payload: |
            {
              "text": "Here’s this week’s Asana milestones:\n```{{ steps.gen.outputs.table }}```"
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
