name: Bi-Daily Weekly Milestones to Slack

on:
  push:
    branches:
      - v1.6
  schedule:
    # Every Monday at 8:30 AM ET → 12:30 UTC
    - cron: '30 12 * * 1'
    # Every Monday at 1:30 PM ET → 17:30 UTC
    - cron: '30 17 * * 1'
  workflow_dispatch:

jobs:
  report:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install requests

      - name: Run weekly milestones script
        env:
          ASANA_PAT:            ${{ secrets.ASANA_PAT }}
          ASANA_WORKSPACE_GID:  ${{ secrets.ASANA_WORKSPACE_GID }}
          SLACK_WEBHOOK_URL:    ${{ secrets.SLACK_WEBHOOK }}
        run: python generate_report.py
